[build.environment]
RUBY_VERSION = "3.1.4"

[[headers]]
  for = "/beta.html"
  [headers.values]
  status = 401

[[redirects]]
  from = "/beta.html"
  to = "/401"
  status = 302
  force = true

[[redirects]]
  from = "/users.json"
  to = "/401"
  status = 302
  force = true

[[redirects]]
  from = "/labs/*"
  to = "/403"
  status = 403
  force = true

[[redirects]]
  from = "/p"
  to = "/.netlify/functions/auth"
  status = 200
  force = true



  
