name: Contribute Materials
description: Use this form to contribute materials to Materio's Library
title: "New Contribution !"
labels: ["material upload", "contribution"]
body:
  - type: input
    id: semester
    attributes:
      label: 🗓 Semester
      placeholder: e.g., 4th Semester
    validations:
      required: true

  - type: input
    id: subject
    attributes:
      label: 📘 Subject
      placeholder: e.g., Operating Systems
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: 📂 Category
      options:
        - Syllabus
        - Chapters
        - Question Banks
        - Assignments
        - Tutorials
        - Reference Book
        - Refrence Tables
        - Miscelleneous
        - Cheatsheet
        - Material Update
        - Other
    validations:
      required: true

  - type: input
    id: topic
    attributes:
      label: 📑 Topic Name (Filename)
      placeholder: e.g., Paging_Algorithms.pdf
    validations:
      required: true

  - type: textarea
    id: file_attachment
    attributes:
      label: Upload File here
      placeholder: Upload Your File here by clicking on the button that says "📎Paste, drop, or click to add files" right below the textarea or **drag & drop** the file in the textarea. Only **1 file per submission** is recommended for clarity.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        If you're having trouble uploading:  
        🔄 Refresh the page and try again OR  
        📩 Mail the resources directly at `materio.operable341@silomails.com` with all the necessary details.

  - type: checkboxes
    id: checklist
    attributes:
      label: "✅ Checklist (**Important**)"
      options:
        - label: "The file name is clear and follows proper naming conventions."
        - label: "The material is relevant and accurate to the best of my knowledge."
    validations: 
      required: true